### ISSUE TITLE
JetStream Subscribe does not reconnect on startup

### ISSUE THREAD

**Issue by piotrpersona** [nats-io/nats.go#1029]
## JetStream Subscribe does not reconnect on startup

Make sure that these boxes are checked before submitting your issue -- thank you!

 - [ ] Included nats.go version
 - [ ] Included a [Minimal, Complete, and Verifiable example] (https://stackoverflow.com/help/mcve)

#### Versions of `nats.go` and the `nats-server` if one was involved:

```
github.com/nats-io/nats.go v1.16.0 // indirect
```

#### OS/Container environment:

macOS Monterey 12.0.1

#### Steps or code to reproduce the issue:

1. Run subscriber without NATS server, with infinite reconnect options:
```go
package main

import (
	"fmt"
	"log"
	"os"
	"os/signal"
	"time"

	"github.com/nats-io/nats.go"
)

func exit(err error) {
	if err != nil {
		log.Println(err)
		os.Exit(1)
	}
}

func main() {
	opts := []nats.Option{
		nats.RetryOnFailedConnect(true),
		nats.MaxReconnects(-1),
		nats.ReconnectWait(time.Second),
		nats.PingInterval(time.Second),
	}
	nc, err := nats.Connect(nats.DefaultURL, opts...)
	exit(err)

	js, err := nc.JetStream(nats.PublishAsyncMaxPending(256))
	exit(err)

	go func() {
		_, err = js.Subscribe("ORDERS.*", func(m *nats.Msg) {
			fmt.Printf("Received a JetStream message: %s\n", string(m.Data))
		}, nats.Durable("MONITOR"))
		if err != nil {
			fmt.Println("js err", err)
		}
	}()

	sigCh := make(chan os.Signal, 1)
	signal.Notify(sigCh, os.Interrupt, os.Kill)
	<-sigCh
}
```

2. Run NATS JetStream via docker-compose
```yaml
version: "3.5"
services:
  nats:
    image: nats
    ports:
      - "4222:4222"
      - "8222:8222"
    command: "-js"
    networks: [ "nats" ]
    volumes:
      - "local-nats:/tmp/nats/jetstream"

networks:
  nats:
    name: nats

volumes:
  local-nats:
```

#### Expected result:

Subscriber should reconnect once NATS is up, in the same way as `nats.Conn.Subscribe` works.

`js.Publish` also works fine. If NATS is not present on startup it will return errors, but once it is up it will reconnect and send messages.

#### Actual result:

Subscriber does not reconnect once NATS is up. Instead

#### Comments

I was debugging, and it seems that `lookupStreamBySubject` returns `timeout` error.
