### ISSUE TITLE
tls certs ignore validation

### ISSUE THREAD

**Issue by alifpay** [nats-io/nats.go#677]
How to ignore tls certs?

I setup load balancer for nats server... 

with browser with cert ignore is working. 

but with nats.go read tcp 192.168.194.23:64488->100.84.15.198:4222: i/o timeout

```
cfg:=&tls.Config{
		InsecureSkipVerify: true,
}
if strings.Contains(natsURL, "tls://") {
	opts = append(opts, nats.Secure(cfg))
}
```

**Comment by ripienaar** [comment]
“I/o timeout” tends to mean the connection could not be established 

for the old balancer it has to be L4 and cannot be doing TLS on the behalf of nats server

**Comment by alifpay** [comment]
Thank you for your reply.
this settings of load balancer
```
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
    service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: '60'
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: 'true'
    service.beta.kubernetes.io/aws-load-balancer-internal: 'true'
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:eu-central-1:xxx:certificate/xxx
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
  name: stan-svc
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app: stan
  ports:
    - protocol: TCP
      port: 4222
      targetPort: 4222

```
